### PR TITLE
Fixed check_acme_routes.sh script

### PR DESCRIPTION
**Pull request by vincenzodnp**
Fixed annotation function's first parameter. 

# Checklist
- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

### CODE REVIEW

**Comment by vincenzodnp** [comment]
@Schnitzel please can you review and merge it, please? Thanks

**Comment by Schnitzel** [comment]
@vincenzodnp converted it into a draft please undraft when you are done

**Comment by vincenzodnp** [comment]
@Schnitzel undrafted. Can you please review it? Thanks

**Comment by tobybellwood** [comment]
should be resubmitted against https://github.com/amazeeio/helper-scripts

**Pull request closed without merging**
