### PR TITLE
Redeploy pods if only the configmap is changed

### LINKED ISSUE #1728: Updating a project's environment variables doesn't actually update those variables within running containers
**Describe the bug**
Whenever an environment variable is created or updated within a project, any running pods are not redeployed. This is due to the fact that the env vars are changed in the `lagoon-env` configmap, which is referenced by the pod. Since this configmap is not actually a part of the pod that's changing, the pod hasn't actually changed and isn't redeployed as a result.

**To Reproduce**
1. Create a new environment variable with a `global` scope
2. See that the newly created environment variable is not reflected in any of the project's containers.

**Expected behavior**
When environment variables are updated, containers should be redeployed accordingly to reflect any updates to those variables.

### PR DESCRIPTION
**Pull request by shreddedbacon**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [x] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

Whenever an environment variable is created or updated within a project, any running pods are not redeployed. This is due to the fact that the env vars are changed in the lagoon-env configmap, which is referenced by the pod. Since this configmap is not actually a part of the pod that's changing, the pod hasn't actually changed and isn't redeployed as a result.

This PR aims to do some initial checks to see if only the configmap has changed, and redeploys any pods if it has.

Added bonus: ~It can check if this is the first time a deployment has occurred and won't try to run any `pre-rollout` tasks.~ Lagoon will now check for the existence of two new VARs during a deployment to see if it should run pre or post rollout tasks instead. These need to be defined in the API as `true`.
```
LAGOON_PREROLLOUT_DISABLED
LAGOON_POSTROLLOUT_DISABLED
```

# Closing issues
closes #1728 #1804

### CODE REVIEW

**Comment by shreddedbacon** [comment]
This will definitely need some :eyes: over it. I haven't fully tested it locally yet.

**Comment by rocketeerbkw** [comment]
>Added bonus: It can check if this is the first time a deployment has occurred and won't try to run any pre-rollout tasks.

Why? What is the problem this addresses? I didn't find an issue and never heard this getting discussed anywhere so I'm just unaware of the background. Are there no use cases where a pre-rollout on first deploy is useful? Could we accomplish the same thing by injecting a `FIRST_DEPLOYMENT` environment variable and then use that in the pre-rollout task itself (so projects can opt-out)?

**Comment by shreddedbacon** [comment]
> > Added bonus: It can check if this is the first time a deployment has occurred and won't try to run any pre-rollout tasks.
> 
> Why? What is the problem this addresses? I didn't find an issue and never heard this getting discussed anywhere so I'm just unaware of the background. Are there no use cases where a pre-rollout on first deploy is useful? Could we accomplish the same thing by injecting a `FIRST_DEPLOYMENT` environment variable and then use that in the pre-rollout task itself (so projects can opt-out)?

Yeah I commented here sort of describing why and came to the same conclusion of a VAR. It has happened occasionally for a few PaaS customers.

https://github.com/amazeeio/lagoon/issues/1804#issuecomment-617515490

But basically, pre-rollout tasks won't run if the pods they need to run in don't exist. So if a pre-rollout task is defined, and it is a first deployment, it will fail until it is removed.

**Comment by shreddedbacon** [comment]
I just found this #1726 so I guess the actual issue of pre-rollout tasks failing was already resolved.
Updated PR to remove my check.

Issue  #1804 of pre-rollout tasks failing in an unrecoverable way, being user controllable without having to ask an administrator for help could be handy, and might have helped with that particular issue. 

I updated the PR to include these new VARs to check for when a deployment occurs. Lagoon will run tasks unless these are set to `true`
```
LAGOON_PREROLLOUT_DISABLED
LAGOON_POSTROLLOUT_DISABLED
```

**Comment by shreddedbacon** [comment]
Closing this as #1923 is a bit simpler

**Pull request closed without merging**
