### PR TITLE
Removes return statement in custom vcl to allow fallback in order to deal with no-cache/private/no-store

### LINKED ISSUE #2065: Varnish-drupal .vcl configuration ignores no-cache, no-store, and private cache control headers
**Describe the bug**
We are getting cache HITs when we have cache control headers 'no-cache, no-store, and private`

**To Reproduce**

Run 
`curl -sLIXGET https://www.amazeelabs.com/.lagoonhealthz | grep Cache`

several times, after the third you'll start seeing 

`X-Varnish-Cache: HIT`

**Expected behavior**

We should not be getting a HIT here, this page should be uncached - I've, further, run tests on the output of the php-healthz script itself to confirm that during the 2 minutes or so that the response is cached that any changes to the output from the script are not propagated through Varnish - that is, the page is genuinely cached.

**Additional context**

The problem seems to be the way we've implemented our `vcl_backend_response` here https://github.com/amazeeio/lagoon/blob/master/images/varnish-drupal/drupal.vcl#L345

Within Varnish, the default hit-for-miss policy is defined in the builtin VCL here -> https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/builtin.vcl#L149

HOWEVER, because there is no path in our own `vcl_backend_response` that _doesn't_ return, the builtin vcl is never actually run. This is suggested by the comments (in the default.vcl implementation from Varnish)

```
# It does not do anything by default, delegating control to the
# builtin VCL. The builtin VCL is called when there is no explicit
# return statement.
```

### PR DESCRIPTION
**Pull request by bomoko**
This PR introduces some VCL from the default.vcl to deal with cache-control scenarios where we're currently caching assets that are explicitly marked for no caching

Before the change, when running the current varnish-drupal image, I'm getting the following (erroneous) behaviour:

```
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/.lagoonhealthz | grep Cache
Cache-Control: must-revalidate, no-cache, private
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/.lagoonhealthz | grep Cache
Cache-Control: must-revalidate, no-cache, private
X-Varnish-Cache: HIT

```

Whereas, locally, after building and using the new varnish-drupal with this PRs changes we have

```
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/.lagoonhealthz | grep Cache
Cache-Control: must-revalidate, no-cache, private
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/.lagoonhealthz | grep Cache
Cache-Control: must-revalidate, no-cache, private
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/.lagoonhealthz | grep Cache
Cache-Control: must-revalidate, no-cache, private
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/.lagoonhealthz | grep Cache
Cache-Control: must-revalidate, no-cache, private
X-Varnish-Cache: MISS
```

Standard responses are still cached
```
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/en | grep Cache
Cache-Control: max-age=900, public
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/en | grep Cache
Cache-Control: max-age=900, public
X-Varnish-Cache: HIT
```

And sessions are uncached, as expected

```
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/en --cookie SSESS123123=12312313 | grep Cache
Cache-Control: max-age=900, public
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/en --cookie SSESS123123=12312313 | grep Cache
Cache-Control: max-age=900, public
X-Varnish-Cache: MISS
bomoko@ADA:/work/Amazee/AmazeeLabsV4_com$ curl -sLIXGET http://amazeelabs-v4.com.docker.amazee.io/en --cookie SSESS123123=12312313 | grep Cache
Cache-Control: max-age=900, public
X-Varnish-Cache: MISS
```

# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

The details are given fully in issue #2065 

# Closing issues
closes #2065

### CODE REVIEW

**Review by seanhamlin — APPROVED** [review]

**Comment by Schnitzel** [comment]
mhh this is weird, I would have expected that varnish never caches a response that has `Cache-Control: must-revalidate, no-cache, private` in the header, so adding this to our varnish config is rather a weird thing.
@bomoko can you research why this might happen? what I know is that varnish has internal subroutines that are executed for every request:
https://varnish-cache.org/docs/trunk/reference/states.html
https://varnish-cache.org/docs/trunk/users-guide/vcl-built-in-subs.html
(not sure if that is the correct varnish version!)
but maybe they are not executed?

**Comment by Schnitzel** [comment]
talked with @bomoko  via slack and he showed me https://github.com/amazeeio/lagoon/issues/2065 where all of my questions are already explained, Mea culpa! 

But we discussed that we would like to copy the whole piece that varnish does in the internal vcl to have feature parity with the default varnish config.

**Comment by bomoko** [comment]
Requested change made, and tested locally - the tests detailed above all still run as expected, and I ran a few other tests looking at cache responses for large vs small ( >= 10MB and < 10MB respectively) and caching works as expected.

**Comment by Schnitzel** [comment]
@bomoko 
mh I thought we discussed that we're gonna copy the code of the default VCL **into** our VCL, as we think that having a hidden vcl that runs somewhere else, that is also not visible easily is confusing?

**Comment by bomoko** [comment]
Sorry @Schnitzel! More crossed wires on slack vs. github.

Change incoming!

**Pull request merged**
