### PR TITLE
Set default strategy to RollingUpdate for Redis in Kubernetes

### LINKED ISSUE #2371: Redis helmchart default strategy
# Describe the bug

Redis kubernetes deployment default strategy is `Recreate` in the helmchart.
`RollingUpdate` expected

## Expected behavior
```
strategy:
    type: RollingUpdate
```

### PR DESCRIPTION
**Pull request by vincenzodnp**
# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

This PR changes the default deployment strategy for `Redis` in kubernetes.
From `Recreate` to `RollingUpdate`.

# Closing issues

closes #2371

### CODE REVIEW

**Review by Schnitzel — APPROVED** [review]

**Comment by Schnitzel** [comment]
@vincenzodnp thanks! can you also cherry-pick this against master and send a PR there? I think this makes sense to also have in 1.x

**Comment by smlx** [comment]
Do we even need to specify a strategy? Rolling update is the default?

**Comment by Schnitzel** [comment]
@smlx good question, for me both is fine :)

**Comment by vincenzodnp** [comment]
I think by specifying it, we are safe if they change the default.

**Pull request merged**
