### PR TITLE
mongodb-shared lagoon.type.

### LINKED ISSUE #890: mongodb shared service type.
At the request of a customer, create a shared mongodb type.

### PR DESCRIPTION
**Pull request by rtprio**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [x] Documentation has been written/updated.
- [x] Changelog entry has been written

The service broker for mongodb permits one larger mongodb instance to serve the mongo needs of several projects at once.

# Changelog Entry
Feature - add mongo-shared service type (#890)

# Closing issues
closes #890
also closes VLAAN-19

### CODE REVIEW

**Review by Schnitzel — DISMISSED** [review]
code looks good! can you please add:
1. A changelog entry
2. Also update the services types list https://lagoon.readthedocs.io/en/latest/using_lagoon/service_types/

**Comment by rtprio** [comment]
> 1. A changelog entry
I've updated this PR to follow the template.

> 2. Also update the services types list https://lagoon.readthedocs.io/en/latest/using_lagoon/service_types/
👌

**Comment by rtprio** [comment]
> 1. A changelog entry
I've updated this pr to follow the template
> 2. Also update the services types list https://lagoon.readthedocs.io/en/latest/using_lagoon/service_types/
done

**Review by rtprio — COMMENTED** [review]
ok

**Review by twardnw — DISMISSED** [review]
Thanks for getting these in

**Review by twardnw — APPROVED** [review]

**Pull request merged**
