### PR TITLE
Switch services to Node.js 16

### PR DESCRIPTION
**Pull request by rocketeerbkw**
# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

Node.js 10 is quite out of date, but we're no longer blocked on old packages, so this upgrades to the latest LTS release.

# Closing issues
n/a

### CODE REVIEW

**Review by tobybellwood — APPROVED** [review]
This looks good - we should keep in the back of our mind that there are a few npm oddities in there still to clean up/upgrade, but nothing that's a dealbreaker at this stage

**Comment by tobybellwood** [comment]
@timclifford - this might interfere with some of your UI refactoring

**Comment by timclifford** [comment]
All good - no issues with the node update for UI branch after merge

Should we update the test images that pull from testlagoon as well?
image

**Comment by tobybellwood** [comment]
I've done that in #2653 😃

**Pull request merged**
