### PR TITLE
Update mariadb.md

### PR DESCRIPTION
**Pull request by justinlevi**
# Checklist

- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

Explain the **details** for making this change. What existing problem does the pull request solve?

# Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by rocketeerbkw** [comment]
That section is about "Connecting to MySQL container from the host" and "connect to whatever database management tool you'd like". The environment variables you listed are only available in the container, so you wouldn't be able to use them for eg Sequel Ace. The `drupal` user/pass/db are all hardcoded in the mariadb-drupal image so would work for external tools.

**Comment by justinlevi** [comment]
Hmm, should this page be renamed to mariadb-drupal then?

**Comment by rocketeerbkw** [comment]
The page you're editing is already under the Drupal section [`docs/drupal/services/mariadb.md`](https://docs.lagoon.sh/lagoon/drupal/services/mariadb). There are other mariadb pages under the docker images section that include environment variable names: https://docs.lagoon.sh/lagoon/docker-images/mariadb and https://docs.lagoon.sh/lagoon/docker-images/mariadb/mariadb-drupal

Looks like there's some duplicate info between the three pages, and maybe it could be organized better.

**Comment by justinlevi** [comment]
My mistake, the docker-images mariaddb page was what I was missing. TY.

**Pull request closed without merging**
