### PR TITLE
Add sub-directory links to root README.md

### LINKED ISSUE #1761: Add links to sub-folder README.md files
The root repository `README.md` file is quite empty, it would be nice to have an overview of what each folder is used for and perhaps link to sub directories which contain `README.md` files.

Something like this might work:

---

### Repository overview

This repository consists of the following:
- [images](/images)
- [cli](/cli)
- [services](/services)

### Services

This project contains the following services:
- [ui](/services/ui/)
- [logs2microsoftteams](/services/logs2microsoftteams/)
- [logs2rocketchat](/services/logs2rocketchat/)
- [kubernetesdeployqueue](/services/kubernetesdeployqueue/)
- [kubernetesremove](/services/kubernetesremove/)
- [kubernetesbuilddeploymonitor](/services/kubernetesbuilddeploymonitor/)
- [logs-db-ui](/services/logs-db-ui/)
- [logs-db](/services/logs-db/)
- [openshiftremove](/services/openshiftremove/)
- [auth-server](/services/auth-server/)
- [ssh](/services/ssh/)
- [openshiftbuilddeploymonitor](/services/openshiftbuilddeploymonitor/)
- [logs2slack](/services/logs2slack/)
- [drush-alias](/services/drush-alias/)
- [webhooks2tasks](/services/webhooks2tasks/)
- [kubernetesbuilddeploy](/services/kubernetesbuilddeploy/)
- [logs2email](/services/logs2email/)
- [openshiftbuilddeploy](/services/openshiftbuilddeploy/)
- [backup-handler](/services/backup-handler/)
- [webhook-handler](/services/webhook-handler/)
- [logs2logs-db](/services/logs2logs-db/)

### PR DESCRIPTION
**Pull request by dan2k3k4**
Fixes #1761

### CODE REVIEW

**Review by AlannaBurke — COMMENTED** [review]
I like adding this, but I think that if we are going to link all of these, they should each have a readme, or we're just kind of sending people into the nether (especially the top-level ones). Thoughts? It looks like some of these do, some of them don't.

**Comment by dan2k3k4** [comment]
Agreed @AlannaBurke - if we list only the ones with `README.md` files, then I think I have to remove the links to: `/images` and `/services` but it could be nice to explain those "top-level" directories in a note.

As for the links to each `/services/<folder>` - they were all the ones with a `README.md` but a few are empty (just markdown title)... so we would need to add a small note in those files to explain what the service does or is used for.

**Comment by AlannaBurke** [comment]
I can work on adding documentation where it's missing and trying to get it if I don't have enough knowledge!

**Comment by dan2k3k4** [comment]
@AlannaBurke I've removed the `Repo over` as it had only 3 sub-folder links which were to places without `README.md` files anyway...

**Comment by AlannaBurke** [comment]
I created this ticket and am reaching out to the devs to get these updated. https://github.com/amazeeio/lagoon/issues/1791

**Review by tobybellwood — APPROVED** [review]
sensible - will review post Lagoon2.0 anyway

**Pull request merged**
