### PR TITLE
Update URL of renamed lagoon-charts repo

### PR DESCRIPTION
**Pull request by rocketeerbkw**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

The repo for lagoon charts was renamed, this updates the URL in the makefile.

# Closing issues
n/a

### CODE REVIEW

**Comment by tobybellwood** [comment]
Tbh we could probably also rename the alias from amazeeio to lagoon-charts - doesn't change much, but explains more?

**Comment by rocketeerbkw** [comment]
Are you talking about this part `repo add amazeeio`? If `amazeeio` can be any string then it probably makes sense to change it too.

**Comment by tobybellwood** [comment]
Yup, it's just an internal reference - it can be anything, but would also need to change in the `update` line too

**Comment by smlx** [comment]
FWIW I just used `lagoon` here: https://uselagoon.github.io/lagoon-charts/

**Pull request merged**
