### PR TITLE
refactor: create make command for external repos and add image repo tags to docker-compose yaml

### PR DESCRIPTION
**Pull request by shreddedbacon**
# General Checklist

- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for inclusion in changelog

# Database Migrations

- [ ] If your PR contains a database migation, it **MUST** be the latest in date order alphabetically

Just refactoring some commands to make them easier for external consumption

### CODE REVIEW

**Review by tobybellwood — APPROVED** [review]
This makes sense and adds flexibility!

**Review by tobybellwood — APPROVED** [review]
This makes sense and adds flexibility!

**Comment by shreddedbacon** [comment]
Just had to rebase and fix conflict due to some other changes to the docker-compose file with keycloak volumes.

**Comment by shreddedbacon** [comment]
can we merge this now?

**Pull request merged**
