### PR TITLE
Configurable elastic endpoints

### LINKED ISSUE #1313: Configurable elasticsearch endpoints
**Describe the bug**
Some services are hardcoded to use `logs-db:9200`. It would be good to be able to specify a custom elasticsearch endpoint.

### PR DESCRIPTION
**Pull request by shreddedbacon**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [x] Changelog entry has been written

This change is to allow `logs-db:9200` to be configurable, this means that either another elasticsearch can be used. Or a service with a `ClusterIP` can be used instead to reduce issues that can come with a headless service and DNS.

# Changelog Entry

Improvement - Allow the `api` to use a configurable elasticsearch endpoint
Improvement - Allow the `auto-idler` to use a configurable elasticsearch endpoint

# Closing issues
closes #1313

### CODE REVIEW

**Comment by tobybellwood** [comment]
would this allow to specify an Elasticsearch located outside Lagoon?

**Comment by shreddedbacon** [comment]
Potentially

**Comment by Schnitzel** [comment]
@shreddedbacon 
that's a great change, though I just switched to use `logs-db-service` by default (which exists since Lagoon 1.1.0

can you update this in this PR? thanks!

**Review by Schnitzel — CHANGES_REQUESTED** [review]
use `logs-db-service` by default, also check that this might cause issues for local development, where we probably need to come up with a clever way to handle this.

**Comment by Schnitzel** [comment]
nice idea! there are more places though where we should use this, see https://github.com/amazeeio/lagoon/commit/47a53ea462dd526203006322c08f549ce2ee9389:
- logs-forwarder
- logs2logs-db 
- logs-db-curator

**Comment by shreddedbacon** [comment]
Yup, will work more on this shortly

**Comment by Schnitzel** [comment]
@shreddedbacon 
please check https://github.com/amazeeio/lagoon/pull/1350/files which solves the problem of local `logs-db-service` in a more elegant version. 
I still like the fact that we can define an external elasticsearch all together, but I think we don't need to have the logic switching between `logs-db` and `logs-db-service` for lagoon anymore

**Comment by shreddedbacon** [comment]
Agree, that is definitely more elegant. I'll re-work this to just allow for configurable ES endpoints only.

**Comment by shreddedbacon** [comment]
I've updated this branch to just being able to configure elastic endpoints using envvars, this goes along with needing #1350 to be merged too.

**Pull request merged**
