### PR TITLE
Record lagoon version in containers

### PR DESCRIPTION
**Pull request by rtprio**
Partially assists with #477 insofar as that one can compare `/etc/lagoon-version` to [the latest release](https://github.com/amazeeio/lagoon/releases/latest), and run the script in #514 .

### CODE REVIEW

**Review by Schnitzel — CHANGES_REQUESTED** [review]
@rtprio 
Instead of adding the `ARG` to ever image, could we just add it to the `commons` image within `/lagoon` as `/lagoon/version`?
this will then be copied by every images already via
https://github.com/amazeeio/lagoon/pull/515/files#diff-3c80f1e8503e7224690d4288bc69620dR10

**Comment by Schnitzel** [comment]
mhh I realize this breaks now all the layer caching of all images.

can we change it to `git describe --abbrev=0 --tags` ? this will show something like:

```
~/git/amazeeio/lagoon (v0.16.0=)$ git describe --tags
v0.15.1-128-g55982fce
~/git/amazeeio/lagoon (v0.16.0=)$ git describe --abbrev=0 --tags
v0.15.1
```

**Comment by rtprio** [comment]
I was trying to express if the image was a released version or some sort of development/hotfix/manually pushed version. 

`git describe --tags --exact-match 2>/dev/null || echo "development"  `
and that should keep caching working.

**Review by rtprio — COMMENTED** [review]
I've revised this so that layer caching is improved.

**Pull request merged**
