### PR TITLE
stop main branch from building base images

### PR DESCRIPTION
**Pull request by tobybellwood**
This PR does a number of things:
1) It removes from /lagoon the base images that are now built at uselagoon/lagoon-images
2) Non-tagged images are now pushed to the testlagoon dockerhub
3) Tagged images will be pushed to uselagoon dockerhub (and the base images not transferred to lagoon-images can be pushed to amazeeio dockerhub) 
4) It references the :latest tag from the uselagoon dockerhub for base images
5) It references the :latest tag from the testlagoon dockerhub for test images
6) both are overridable with UPSTREAM_REPO and UPSTREAM_TAG (test images may have to be sed'ded if we can't work out where to add the build-arg)

This branch was derived from the lagoon-core branch, so there are a few changes to the test image and api-data-watcher pusher.  I'd suggest that those changes be merged in first?

# Checklist

- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [x] PR title is ready for changelog and subsystem label(s) applied

### CODE REVIEW

**Comment by tobybellwood** [comment]
This is part of a triple-PR.

There is a PR to usealgoon/lagoon-images https://github.com/uselagoon/lagoon-images/pull/20) that removes the final images that are being built over at amazeeio/lagoon

There is a PR to amazeeio/lagoon (master) https://github.com/amazeeio/lagoon/pull/2242 that removes the images built in the lagoon-images repo for all master (Lagoon 1.x) builds).  Lagoon master will push tagged service images to amazeeiolagoon as before, and tagged base images to amazeeio (but not update `latest` tag)

There is a PR to amazeeio/lagoon (main) https://github.com/amazeeio/lagoon/pull/2236 that removes the images built in the lagoon-images repo for all main (Lagoon 2.x) builds).  Lagoon main will push tagged service images to uselagoon, and tagged base images to uselagoon (and update `latest` tag).  In addition, legacy base images will also have a tag pushed to amazeeio.

In addition:
* the lagoon main & master branches are now configured to build their images from the `latest` tagged base images, published under `uselagoon` dockerhub.
* the test suites for main & master branches are now configured to build the `main` tagged images in the `testlagoon` dockerhub - i.e. test the latest pushes to main.

Notes on images

* yarn-workspace-builder, kubectl-build-deploy-dind, oc-build-deploy-dind, oc and kubectl, docker-host and curator have all been left in Lagoon as there isn't much need for them outside of Lagoon - in addition, this allows for the images to diverge for Lagoon 1.x/2.x
* athenapdf-service, rabbitmq and rabbitmq-cluster have also been left in lagoon, as there may be no use for them outside Lagoon.  These images can obviously be moved back at some point if needed.

**Comment by smlx** [comment]
A bunch of these commits are also in https://github.com/amazeeio/lagoon/pull/2212, maybe you could merge that one first and rebase to make this PR less noisy?

**Comment by tobybellwood** [comment]
(agreed - I extended that one I think!)

**Comment by tobybellwood** [comment]
closing for #2316

**Pull request closed without merging**
