### PR TITLE
Release 0.6

### PR DESCRIPTION
**Pull request by Schnitzel**

### CODE REVIEW

**Comment by twardnw** [comment]
hmm, did we not switch from sitegroup to project yet? The branch tests show good, but the final POST to slack in there has a validation error for SiteGroupName

**Comment by Schnitzel** [comment]
@twardnw do you have a link to the POST you are talking about?

**Comment by twardnw** [comment]
Last stage : https://lagoon-ci.amazeeio.cloud/blue/organizations/jenkins/lagoon/detail/develop/68/

**Comment by Schnitzel** [comment]
Ah! During the deployment we talks to the production Lagoon which then will deploy a new version of the develop Lagoon. The production Lagoon is still on the master branch which does not know anything about the `sitegroup` to `project` change, that's why it fails.

But this is something that we need to wait for until we have merged into master and moved everything from appuio to a regular OpenShift :)

**Comment by twardnw** [comment]
👍

**Pull request merged**
