### PR TITLE
WIP: add support for service specific autogenerated route disabling

### PR DESCRIPTION
**Pull request by shreddedbacon**
…pose.yml

 

# Checklist

- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated
- [ ] PR title is ready for changelog and subsystem label(s) applied

Explain the **details** for making this change. What existing problem does the pull request solve?

# Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by tobybellwood** [comment]
On review of this, it appears that the routes are still being created for the false condition.

This is because there are two `kubectl apply` cycles in each build.

The first is targeted at the services and routes created in `/kubectl-build-deploy/lagoon/services-routes`, which rightly excludes the skipped routes (applied [here](https://github.com/uselagoon/lagoon/blob/main/images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh#L1365))
and the second is targeted at `/kubectl-build-deploy/lagoon/deploymentconfigs-pvcs-cronjobs-backups` (applied [here](https://github.com/uselagoon/lagoon/blob/main/images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh#L1684))

However, this second folder runs a straight `helm template` on the service, which creates the service and ingress anyway (one of the three calls in [this](https://github.com/uselagoon/lagoon/blob/main/images/kubectl-build-deploy-dind/scripts/exec-kubectl-resources-with-images.sh#L19) file

My general feeling is that this second apply shouldn't be reapplying the ingress and services from earlier anyway.

**Comment by tobybellwood** [comment]
ok - so I've fixed that up in my branch, and written tests - will discuss with @shreddedbacon Monday.

Basically, I've purged the service, ingress and DBaaS charts from the template after they've been applied to ensure that they don't get applied twice.

Also fixed up the issue from #2846 whilst I was at it

https://github.com/shreddedbacon/lagoon/compare/service-autoroutes...tobybellwood:service-autoroutes

**Comment by shreddedbacon** [comment]
Wow, there were more changes than I expected required, we reference something way more than I imagined we did

**Comment by shreddedbacon** [comment]
Closing because this is addressed in the `build-deploy-tool`

**Pull request closed without merging**
