### PR TITLE
nginx drupal: allow access to all files in sites/*/files

### PR DESCRIPTION
**Pull request by Schnitzel**

### CODE REVIEW

**Comment by dasrecht** [comment]
Looks good to me. Go ahead to merge

**Review by dasrecht — COMMENTED** [review]
Looks good to me. Go ahead to merge

**Review by dasrecht — APPROVED** [review]
Looks good to me. Go ahead to merge

**Comment by Schnitzel** [comment]
merged thanks for review @dasrecht

**Pull request merged**
