### PR TITLE
HSTS Updates

### PR DESCRIPTION
**Pull request by rocketeerbkw**
# Checklist

- [x] Affected Issues have been mentioned in the Closing issues section
- [x] Documentation has been written/updated
- [x] PR title is ready for inclusion in changelog

* Minor fixes to docs regarding HSTS and how it's supported in kubernetes
* Re-formatting and re-phrasing of the environment routes section
* Enable testing for HSTS on k8s

image

image

image

# Closing issues

n/a

### CODE REVIEW

**Comment by rocketeerbkw** [comment]
TIL that `insecure: None` doesn't work anymore, it's [treated the same as `Redirect`](https://github.com/uselagoon/build-deploy-tool/blob/620efad3c6ac7241ad19fa2c1e7f2ed890a71066/internal/templating/ingress/templates_ingress.go#L127). This should be updated in the docs.

**Comment by tobybellwood** [comment]
The error in the test here I think is related to the newly added hstsEnabled boolean? It shows up as a pre-rollout error, but that's the first time golang parses the file I think?

`Error: couldn't unmarshal file .lagoon.yml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Environment.environments.routes of type bool`

**Comment by rocketeerbkw** [comment]
Updated the docs (screenshots updated) and fixed the tests. This PR includes a change to the makefile to checkout a lagoon-charts branch, so if the tests pass :crossed_fingers: wait to merge until that change is reverted.

**Comment by tobybellwood** [comment]
now https://github.com/uselagoon/lagoon-charts/pull/549 has merged, CHARTS_TREEISH can be reverted

**Comment by rocketeerbkw** [comment]
Thanks, fixed a merge conflict with monitoring_urls PR and removed the CHARTS_TREEISH commit

**Pull request merged**
