### PR TITLE
API Automated Billing Calculations

### PR DESCRIPTION
**Pull request by justinlevi**
# Checklist
- [ ] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [ ] Changelog entry has been written

Implements API BillingCost Calculations for lagoon projects.

To run the billing calculations unit tests, on your host machine:
```
$ cd services/api
$ yarn
$ yarn test billingCalculations
```

You can run individual tests by filtering via the tags at the end of each test description:
```
$ yarn test billingCalculations -t "#storage #USD #FC"
```

To test the billing calculation resolvers:
```
$ cd services/api && yarn test resolvers -t "#billing"
```

# Changelog Entry
Adding in lagoon billing calculations to the API

### CODE REVIEW

**Comment by Schnitzel** [comment]
sorry, another conflict @justinlevi can you check that one as well? thank you.

**Comment by wintercreative** [comment]
> sorry, another conflict @justinlevi can you check that one as well? thank you.

np - rebased and pushed.

**Comment by Schnitzel** [comment]
mhh it is failing with 
```
$ tsc --pretty

src/helpers/sync-groups-opendistro-security.ts:14:31 - error TS2349: This expression is not callable.

  Each member of the union type '(<U>(callbackfn: (value: Group, index: number, array: Group[]) => U, thisArg?: any) => U[]) | (<U>(callbackfn: (value: BillingGroup, index: number, array: BillingGroup[]) => U, thisArg?: any) => U[])' has signatures, but none of those signatures are compatible with each other.


14   let groupsQueue = allGroups.map(group => ({ group, retries: 0}));

                                 ~~~



Found 1 error.
```

**Comment by Schnitzel** [comment]
tests passed, @rocketeerbkw can you do a last codereview and give your go ahead for a merge?

**Comment by Schnitzel** [comment]
@justinlevi unfortunately there are now more conflicts :( sorry/

**Comment by justinlevi** [comment]
ok, I think I have fixed the merge conflict.

**Pull request merged**
