### PR TITLE
Added `scripts` directory from `drupal-example` repository

### LINKED ISSUE #1101: Missing `scripts` directory in docs/using_lagoon/drupal examples
**Describe the bug**
Build of `cli` service fails because in Dockerfile.cli of drupal8-compose examples, there is a `COPY` statement related to not existent `scripts` directory.

Looking at https://github.com/amazeeio/drupal-example repo, the `scripts` directory should exist and should have a `composer` subfolder with a `ScriptHandler.php` file.

**To Reproduce**
1. Use example files from https://github.com/amazeeio/lagoon/tree/master/docs/using_lagoon/drupal/drupal8-composer-mariadb
2. Run `docker-compose up`

**Expected behavior**
Build of `cli` service

### PR DESCRIPTION
**Pull request by vincenzodnp**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [ ] Documentation has been written/updated.
- [ ] Changelog entry has been written

In `docs/using_lagoon/drupal/drupal8-composer-*` example directories, the `scripts` directory was missing, causing the failure of `cli` container build.

# Changelog Entry

Bugfix - Added `scripts` directory to `composer` projects example dirs (#1101)

# Closing issues
closes #1101

### CODE REVIEW

**Comment by fjgarlin** [comment]
The `scripts` folder is no longer included in the latest versions of Drupal 8 and the files in it are not referenced by the `composer.json` file, so I suggest to comment out the following two lines instead and just add a comment about that if the folder is present we can just uncomment:
* https://github.com/amazeeio/lagoon/blob/master/docs/using_lagoon/drupal/drupal8-composer-mariadb/cli.dockerfile#L4
https://github.com/amazeeio/lagoon/blob/master/docs/using_lagoon/drupal/drupal8-composer-postgres/cli.dockerfile

**Comment by Schnitzel** [comment]
@fjgarlin 
that sounds like a good idea, can you send us a PR for this? (in a new PR)

**Comment by fjgarlin** [comment]
I just did that @Schnitzel . See https://github.com/amazeeio/lagoon/pull/1669

**Comment by tobybellwood** [comment]
Superseded by #1669

**Pull request closed without merging**
