### PR TITLE
Upgrade GraphQL to v14

### LINKED ISSUE #1413: Upgrade graphql to v14
The codebase currently uses graphql library 0.13.x. The latest version is 14.5.8. 14.x was released in August 2018 and has had several releases since 14.0.0. I think the main reason 14.x was released was to better follow semver and to "drop support for node v4 and v9". https://github.com/graphql/graphql-js/releases/tag/v14.0.0

As we update code and add new features, we may soon find that newer libraries require the latest graphql version.

### PR DESCRIPTION
**Pull request by JohnAlbin**
# Checklist
- [x] Affected Issues have been mentioned in the Closing issues section
- [x] ~Documentation has been written/updated.~ n/a
- [x] Changelog entry has been written

The codebase currently uses graphql library 0.13.x. The latest version is 14.5.8. 14.x was released in August 2018 and has had several releases since 14.0.0. I think the main reason 14.x was released was to better follow semver and to "drop support for node v4 and v9". https://github.com/graphql/graphql-js/releases/tag/v14.0.0

In #1279, there's a new node library I want to add and it has a peer dependency on the latest graphql. If updating graphql doesn't work, I'll have to find an old version of this new library that supports 0.13.x.

# Changelog Entry
Improvement - Updates `graphql` library to v14 from v0.13. (#1413)

# Closing issues
Closes #1413

### CODE REVIEW

**Comment by JohnAlbin** [comment]
I'm hoping the tests don't fail as I don't have a reliable way to test them locally.

**Comment by JohnAlbin** [comment]
Screen Shot 2019-11-19 at 10 08 05 PM

*sobs*

**Comment by JohnAlbin** [comment]
Jenkins error shows:

```
FAILED - RETRYING: Drupal 8 composer PHP 7.0 - POSTGRES - Check if URL
 http://nginx.ci-drupal-postgres.drupal8-composer-70-postgres.192.168.99.100.xip.io
 contains content LAGOON_GIT_SHA=c2ac56fb554b56136b4bd7473ef71c9cce440d38
 (1 retries left).

fatal: [localhost]: FAILED! => {"attempts": 90, "cache_control": "no-cache",
 "changed": false, "connection": "close", "content": "<html><body><h1>504
 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n",
 "content_type": "text/html", "msg": "Status code was 504 and not [200]: HTTP
 Error 504: Gateway Time-out", "redirected": false, "status": 504,
 "url": "http://nginx.ci-drupal-postgres.drupal8-composer-70-postgres.192.168.99.100.xip.io"
}
```

Is this just a temporary error?

**Comment by JohnAlbin** [comment]
I've kicked off another Jenkins test. *keeps fingers crossed*

**Comment by Schnitzel** [comment]
@JohnAlbin 
we see other tests also failing at postgres, so something is off there. 
I'm currently investigating what is wrong there.

**Comment by Schnitzel** [comment]
found it: https://github.com/amazeeio/lagoon/pull/1419

**Comment by JohnAlbin** [comment]
Tests passed!

**Pull request merged**
